version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: the raw data 
    tables:
      - name: sales
        identifier: '1'
        description: sales model
        columns:
          - name: date_date
            description: purchase date
          - name: orders_id
            description: id of orders
          - name: products_id
            description: id of products
          - name: revenue
            description: revelue of sales
          - name: quantity
            description: sales qauntity
      - name: products
        identifier: '2 products'
        description: products' model
        columns:
          - name: products_id
            description: the primary key of the products
          - name: purchase_price
            description: price of purchase
            tests: 
              - unique
              - not_null
      - name: shipping
        identifier: '3 shipping'
        description: shipping model
        columns:
          - name: orders_id
            description: the primary key of the shipping table
          - name: shipping_fee
            description: fee of shipping
          - name: logcost
            description: log_cost
          - name: ship_cost
            description: cost_of_shipping
            tests: 
              - unique
              - not_null
              

